version: '3.9'
name: kong-api-gateway

services:
  api1:
    container_name: api1
    build: ./endpoint/
    ports:
      - 5001:300
    environment:
      - ENDPOINT_VERSION=1

  api2:
    container_name: api2
    build: ./endpoint/
    ports:
      - 5002:3000
    environment:
      - ENDPOINT_VERSION=2
      
  api3:
    container_name: api3
    build: ./endpoint/
    ports:
      - 5003:3000
    environment:
      - ENDPOINT_VERSION=3

  kong-dbless:
    container_name: kong
    image: kong:2.8.1-alpine
    ports:
      - 8000:8000
      - 8443:8443
      - 127.0.0.1:8001:8001 
      - 127.0.0.1:8444:8444
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.json
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    volumes:
      - ./kong/:/kong/declarative/

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus