version: '3.9'
name: kong-api-gateway

services:
  endpoint_1:
    container_name: endpoint1
    build: ./endpoint/
    ports:
      - "5001:3001"
    environment:
      - ENDPOINT_VERSION=1
      - PORT_NUMBER=3001

  endpoint_2:
    container_name: endpoint2
    build: ./endpoint/
    ports:
      - "5002:3002"
    environment:
      - ENDPOINT_VERSION=2
      - PORT_NUMBER=3002
      
  endpoint_3:
    container_name: endpoint3
    build: ./endpoint/
    ports:
      - "5003:3003"
    environment:
      - ENDPOINT_VERSION=3
      - PORT_NUMBER=3003

  kong-dbless:
    container_name: kong
    image: kong:2.8.1-alpine
    ports:
      - 8000:8000
      - 8443:8443
      - 127.0.0.1:8001:8001 
      - 127.0.0.1:8444:8444
    environment:
      - name=value
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    volumes:
      - ./kong/:/kong/declarative/