global:
  scrape_interval: 30s

scrape_configs:
  - job_name: prometheus

    static_configs:
      - targets: ['kong:8001']
        labels:
          group: kong

      - targets: ['127.0.0.1:9090']
        labels:
          group: prometheus
